apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce # This volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 1Gi # Request 1 Gigabyte of storage for PostgreSQL

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db
spec:
  replicas: 1 # Run a single instance of the database
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:14.5 # Using the same image as in docker-compose
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "mydatabase" # Match your database name
        - name: POSTGRES_USER
          value: "myuser" # Match your database user
        - name: POSTGRES_PASSWORD
          value: "mypassword" # Match your database password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data # This is where Postgres stores its data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim # Link to the PersistentVolumeClaim
---
apiVersion: v1
kind: Service
metadata:
  name: db # This service name will be used by other applications to connect to the database
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432 # Port for the service
      targetPort: 5432 # Port of the container

