version: '3.8'

services:
  
  db:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb
    volumes:
      - db-data:/var/lib/postgresql/data 
   
  
  apache:
    build: ./apache 
    ports:
      - "80:80" 
    depends_on:
      - service1 
      - service2
      - service3
    
    environment:
      - APACHE_SERVER_NAME=localhost

  
  service1:
    build: ./service1 
    depends_on:
      - db 
   
    
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8080 

  
  service2:
    build: ./service2 
    depends_on:
      - db 
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8080


  service3:
    build: ./service3 
    depends_on:
      - db 
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8080

volumes:
  db-data: 

