services:
  session-app-1:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    networks:
      - session-network
    container_name: session-app-1

  session-app-2:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SERVER_PORT=8080
    networks:
      - session-network
    container_name: session-app-2

  session-app-3:
    build: .
    ports:
      - "8082:8080"
    environment:
      - SERVER_PORT=8080
    networks:
      - session-network
    container_name: session-app-3

networks:
  session-network:
    driver: bridge